name: teguhai_p2p_chat
description: Aplikasi TeguhAi — Obrolan, Video, Belanja & Radio
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # — Inti Supabase —
  supabase_flutter: ^2.5.17

  # — Kirim Gambar & Foto —
  image_picker: ^1.1.2

  # — Kirim Dokumen/PDF —
  file_picker: ^8.1.2

  # — Pilih Emoji —
  emoji_picker_flutter: ^2.3.0

  # — Panggilan Suara & Video (nanti dipakai) —
  flutter_webrtc: ^0.11.6

  # — Buka Tautan/Eksternal —
  url_launcher: ^6.3.0

  # — Format Waktu/Tanggal —
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
